alias ll='ls -Agh'
alias lt='ls -gh'
alias ..='cd ..'
alias ...='cd ../..'
alias open='xdg-open'
alias doc='cd ~/Documents'
alias dow='cd ~/Downloads/'
alias ufsc='cd ~/Documents/UFSC'
alias geem='cd ~/Documents/GEEM'
alias repos='cd ~/Repos'
alias jupiter='ssh mrauen@150.162.31.2 -p 2222'
alias orca='~/.orca/orca'
alias orcaplot='~/.orca/orca_plot'
alias po='poweroff'
alias chemcraft='cd ~/.wine/drive_c/Chemcraft/Chemcraft.exe'
alias killwine='wineserver -k'
alias gplot='gnuplot'

